name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  branch-check:
    if: ${{ github.event_name == 'pull_request' && github.hef == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Source Branch Check
        run: |
          SOURCE_BRANCH=${GITHUB_BASE_REF}

          if [[ ${SOURCE_BRANCH} =~ ^stage ]]; then
            echo SOURCE_BRANCH: $SOURCE_BRANCH
          elif [[ ${SOURCE_BRANCH} =~ ^hotfix ]]; then
            echo SOURCE_BRANCH: $SOURCE_BRANCH
          else
            exit 1
          fi

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Cehckout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 16.x
          registry-url: https://registry.npmjs.org

      - name: install
        run: echo "eslint"

  eslint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org

      - name: eslint
        run: echo "eslint"
