name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: Source Branch Check
        if: ${{ github.event_name == 'pull_request' && github.base_ref == 'master' }}
        run: |
          SOURCE_BRANCH=$GITHUB_HEAD_REF

          echo SOURCE_BRANCH: $SOURCE_BRANCH
          echo TARGET_BRANCH: $GITHUB_BASE_REF

          if [[ ! ${SOURCE_BRANCH} =~ ^(stage|hotfix|feature) ]]; then
            echo Not Allowed
            exit 1
          fi

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Cehckout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 16.x
          registry-url: https://registry.npmjs.org

      - name: install
        run: echo "eslint"

  eslint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org

      - name: eslint
        run: echo "eslint"

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            :aws: *Desktop*
            > Deployed to Prod (${{ job.status }})
            >
            > $(git log --no-merges -1 --oneline)
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
